name: Test MATLAB things
on: workflow_dispatch
jobs:
  matlab-test:
    name: Test MATLAB commands
    runs-on: macos-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Install MATLAB
        uses: matlab-actions/setup-matlab@v2
      - name: Run commands
        run: cat "/Users/runner/hostedtoolcache/MATLAB/2023.2.999/x64/MATLAB.app/licenses/license.dat"
