name: Test MATLAB things
on: workflow_dispatch
jobs:
  matlab-test:
    name: Test MATLAB commands
    runs-on: macos-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Install MATLAB
        uses: matlab-actions/setup-matlab@v2
        with:
          cache: true
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
